
```java
public class Run {
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
            thread.start();
            Thread.sleep(2000);
            thread.interrupt();
        } catch (InterruptedException e) {
            System.out.println("main catch");
            e.printStackTrace();
        }
        System.out.println("end!");
    }
}
```
程序运行结果如图1 - 44所示。

![image](https://github.com/user-attachments/assets/74222913-034e-45e6-bbed-c946775aa358)


上面示例虽然停止了线程，但如果for语句下面还有语句，那么程序还会继续运行。创建测试项目t13forprint，类MyThread.java代码如下：
```java
package exthread;
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        for (int i = 0; i < 500000; i++) {
            if (this.interrupted()) {
                System.out.println("已经是停止状态了！我要退出了！");
                break;
            }
            System.out.println("i=" + (i + 1));
        }
        System.out.println("我被输出，如果此代码是for又继续运行，线程并未停止！");
    }
}
```
文件Run.java代码如下：
```java
package test;
import exthread.MyThread;
import exthread.MyThread;
public class Run {
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
```


```java
            thread.start();
            Thread.sleep(2000);
            thread.interrupt();
        } catch (InterruptedException e) {
            System.out.println("main catch");
            e.printStackTrace();
        }
        System.out.println("end!");
    }
}
```
程序运行结果如图1 - 45所示。

![image](https://github.com/user-attachments/assets/11f71f21-2308-4036-a84b-0febf7cfbdd1)


如何解决语句继续运行的问题呢？看一下更新后的代码。

创建t13_1项目，类MyThread.java代码如下：
```java
package exthread;
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        try {
            for (int i = 0; i < 500000; i++) {
                if (this.interrupted()) {
                    System.out.println("已经是停止状态了！我要退出了！");
                    throw new InterruptedException();
                }
                System.out.println("i=" + (i + 1));
            }
            System.out.println("我在for下面");
        } catch (InterruptedException e) {
            System.out.println("进MyThread.java类run方法中的catch了！");
            e.printStackTrace();
        }
    }
}
```
注意

为了彻底中断线程，需要保证run()方法内部只有一个try - catch语句块，不要出现多个try - catch块并列的情况。

类Run.java代码如下：
```java
package test;
import exthread.MyThread;
```


```java
public class Run {
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
            thread.start();
            Thread.sleep(2000);
            thread.interrupt();
        } catch (InterruptedException e) {
            System.out.println("main catch");
            e.printStackTrace();
        }
        System.out.println("end!");
    }
}
```
运行结果如图1 - 46所示。

![image](https://github.com/user-attachments/assets/b57d04b7-796b-4d8d-ba55-ed7e2b2da47a)


图1 - 46 运行结果

线程终于被正确停止了！此种方式就是前面章节介绍过的第三种停止线程的方法：使用interrupt方法中断线程。

### 1.11.5 在sleep状态下停止

如果线程在sleep状态下，停止线程会是什么样的效果呢？

新建项目t14，类MyThread.java代码如下：

```java
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        try {
            System.out.println("run begin");
            Thread.sleep(200000);
            System.out.println("run end");
        } catch (InterruptedException e) {
```


```java
            System.out.println("在沉睡中被停止！进入catch!"+this.isInterrupted());
            e.printStackTrace();
        }
    }
}
```
文件Run.java代码如下：
```java
public class Run {
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
            thread.start();
            Thread.sleep(200);
            thread.interrupt();
        } catch (InterruptedException e) {
            System.out.println("main catch");
            e.printStackTrace();
        }
        System.out.println("end!");
    }
}
```
程序运行结果如图1 - 47所示。

![image](https://github.com/user-attachments/assets/b74df0a6-a14c-40d5-bfcd-bf68815c6db6)


从运行结果来看，如果线程在sleep状态下停止，则该线程会进入catch语句，并且清除停止状态值，变成false。

上述项目是先调用sleep()，再调用interrupt()方法停止，还有一个反操作在学习线程时也要注意，即先调用interrupt()方法，再调用sleep()方法，但这种方法也会出现异常。

新建项目t15，类MyThread.java代码如下：

```java
public class MyThread extends Thread {
    @Override
    public void run() {
        super.run();
        try {
            for(int i=0;i<100000;i++){
                System.out.println("i="+(i+1));
            }
            System.out.println("run begin");
            Thread.sleep(200000);
            System.out.println("run end");
        } catch (InterruptedException e) {
            System.out.println("先停止，再遇到了sleep!进入catch!");
            e.printStackTrace();
        }
    }
}
```




类Run.java代码如下：
```java
public class Run {
    public static void main(String[] args) {
        MyThread thread = new MyThread();
        thread.start();
        thread.interrupt();
        System.out.println("end!");
    }
}
```
程序执行结果如图1 - 48所示。

![image](https://github.com/user-attachments/assets/c552f714-c960-42d4-8c9b-9903f63b1a30)


控制台最下面的输出如图1 - 49所示。

![image](https://github.com/user-attachments/assets/853f2973-37a5-4f37-a30c-34ef5dc3bccd)


不管其调用顺序，只要interrupt()和sleep()方法碰到一起就会出现异常：

1）在sleep状态执行interrupt()方法会出现异常；

2）调用interrupt()给线程打了中断标记，再执行sleep()方法也会出现异常。

### 1.11.6 使用stop()暴力停止线程

使用stop()方法可以强行停止线程，即暴力停止线程。

新建项目useStopMethodThreadTest，文件MyThread.java代码如下：

```java
package testpackage;
public class MyThread extends Thread {
    private int i = 0;
    @Override
    public void run() {
        try {
            while (true) {
                i++;
                System.out.println("i=" + i);
                Thread.sleep(1000);
            }
        } catch (InterruptedException e) {
            //TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
```



文件Run.java代码如下：

```java
package test.run;
import testpackage.MyThread;
public class Run {
    public static void main(String[] args) {
        try {
            MyThread thread = new MyThread();
            thread.start();
            Thread.sleep(8000);
            thread.stop();
        } catch (InterruptedException e) {
            //TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
}
```
程序运行结果如图1 - 50所示。

![image](https://github.com/user-attachments/assets/ea2ecc74-6299-46e3-a1f1-01255a26b600)


图1 - 50 线程被暴力停止后运行图标呈灰色

由运行结果可以看出，线程被暴力停止了，这种方式就是1.11节介绍的第二种停止线程的方法——使用stop方法强行终止线程。

stop()方法呈删除线程状态，是作废过期的方法，原因就是stop()方法容易造成业务处理的不确定性。例如，A线程执行如下业务：


增加数据1


增加数据2

增加数据3

增加数据4

增加数据5

增加数据6

增加数据7

这时在任意时机对A线程调用stop()方法，A线程均不能确定在哪里被停止了，导致数据增加得不完整。被stop()暴力停止的线程连一个类似执行finally{}语句的机会都没有，就彻底被杀死。

在本节中，线程是否被暴力停止由外界（main方法）决定，线程也可以根据判断条件自己调用stop()方法完成对自身的暴力停止，请看下节的章节。
### 1.11.7 方法stop()与java.lang.ThreadDeath异常

创建测试项目killSelf，文件MyThread.java代码如下：

```java
package test;
public class MyThread extends Thread {
    @Override
    public void run() {
        try {
            Thread.sleep(2000);
            int i = 100;
            System.out.println("begin");
            if (i == 100) {
                this.stop();
            }
            System.out.println(" end");
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
创建运行类代码如下：
```java
package test;
public class Test {
    public static void main(String[] args) throws InterruptedException {
        MyThread thread = new MyThread();
        thread.start();
    }
}
```
程序运行结果如下：

begin

线程MyThread被自身调用stop()方法暴力停止。


自身调用stop()方法时会抛出java.lang.ThreadDeath异常，但在默认的情况下，此异常不需要显式捕捉。

创建测试项目runMethodUseStopMethod，文件MyThread.java代码如下：
```java
package testpackage;
public class MyThread extends Thread {
    @Override
    public void run() {
        try {
            this.stop();
        } catch (ThreadDeath e) {
            System.out.println("进入了catch()方法！");
            e.printStackTrace();
        }
    }
}
```
文件Run.java代码如下：
```java
package test.run;
import testpackage.MyThread;
public class Run {
    public static void main(String[] args) {
        MyThread thread = new MyThread();
        thread.start();
    }
}
```
程序运行结果如图1 - 51所示。

![image](https://github.com/user-attachments/assets/865b34ca-59dc-47f1-8c08-cfdc696bab75)


线程自身调用stop()方法会进入catch(ThreadDeath e)代码块，外界调用stop()方法后线程内部也会进入catch(ThreadDeath e)代码块，下面进行测试。

创建测试项目ThreadDeathTest，创建测试类代码如下：

```java
package test;
public class MyThread extends Thread {
    @Override
    public void run() {
        try {
            for (int i = 0; i < 5000000; i++) {
                System.out.println(i + 1);
            }
        } catch (ThreadDeath e) {
            e.printStackTrace();
```


```java
            System.out.println("进入了MyThread中的catch (ThreadDeath e)代码块中");
        }
    }
}
```

创建运行类代码如下：
```java
package test;
public class Test {
    public static void main(String[] args) throws InterruptedException {
        MyThread thread = new MyThread();
        thread.start();
        Thread.sleep(1000);
        try {
            thread.stop();
        } catch (ThreadDeath e) {
            System.out.println("进入了Test类中的catch (ThreadDeath e)代码块中");
            e.printStackTrace();
        }
    }
}
```
程序运行结果如下：

198012

198013

198014进入了MyThread中的catch (ThreadDeath e)代码块中


java.lang.ThreadDeath

at java.lang.Thread.stop(Unknown Source)

at test.Test.main(Test.java:9)

控制台输出如下信息：

进入了MyThread中的catch (ThreadDeath e)代码块中

在外界对线程对象调用stop()方法后，线程内部会抛出ThreadDeath异常。外界不会抛出ThreadDeath异常，因为信息“进入了Test类中的catch (ThreadDeath e)代码块中”并没有输出。
### 1.11.8 使用stop()释放锁导致数据结果不一致

本节将讲解使用stop()释放锁给数据造成不一致性的结果，如果出现这样的情况，程序处理的数据完全有可能遭到破坏，最终导致程序执行的流程是错误的，在此一定要注意。下面来看一个示例。

创建项目stopThrowLock，文件MyService.java代码如下：
```java
package service;
public class MyService {
```


```java
private String username = "a";
private String password = "aa";
synchronized public String getUsername() {
    return username;
}
synchronized public String getPassword() {
    return password;
}
synchronized public void printString(String username, String password) {
    try {
        this.username = username;
        Thread.sleep(10000000);
        this.password = password;
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
```
调用业务方法printString()的线程代码如下：
```java
package extthread;
import service.MyService;
public class MyThreadA extends Thread {
    private MyService object;
    public MyThreadA(MyService object) {
        super();
        this.object = object;
    }
    @Override
    public void run() {
        object.printString("b", "bb");
    }
}
```
输出数据的线程代码如下：
```java
package extthread;
import service.MyService;
public class MyThreadB extends Thread {
    private MyService object;
    public MyThreadB(MyService object) {
        super();
        this.object = object;
    }
    @Override
    public void run() {
        System.out.println(object.getUsername() + " " + object.getPassword());
        System.out.println("  end " + System.currentTimeMillis());
    }
}
```
文件Run.java代码如下：
```java
package test;
import extthread.MyThreadA;
import extthread.MyThreadB;
import service.MyService;
public class Run {
    public static void main(String[] args) throws InterruptedException {
        MyService service = new MyService();
        MyThreadA myThreadA = new MyThreadA(service);
        MyThreadB myThreadB = new MyThreadB(service);
        myThreadA.start();
        Thread.sleep(500);
        myThreadB.start();
        System.out.println("begin " + System.currentTimeMillis());
        Thread.sleep(5000);
        myThreadA.stop();
    }
}
```
程序运行结果如图1 - 52所示。

图1 - 52 强制stop造成数据不一致

![image](https://github.com/user-attachments/assets/87c2d40a-0f54-408c-bc5c-21fcb9378316)


当执行stop()方法后MyThreadA才会释放锁，线程MyThreadB才能执行同步的get()方法，并且synchronized同步的getUsername()和getPassword()方法取出的是未处理完成的半成品错误数据。

由于stop()方法已经在JDK中被标为“作废/过期”的方法，显然它在功能上具有缺陷，所以不建议在程序中使用stop()方法停止线程。
### 1.11.9 使用return;语句停止线程的缺点及相应的解决方案

将interrupt()方法与return;语句结合使用也能实现停止线程的效果。

创建测试项目useReturnInterrupt，线程类MyThread.java代码如下：
```java
package extthread;
public class MyThread extends Thread {
    @Override
    public void run() {
        while (true) {
            if (this.isInterrupted()) {
                System.out.println("停止了！");
                return;
            }
            System.out.println("timer=" + System.currentTimeMillis());
        }
    }
}
```
运行类Run.java代码如下：
```java
package test.run;
import extthread.MyThread;
public class Run {
    public static void main(String[] args) throws InterruptedException {
        MyThread t=new MyThread();
        t.start();
        Thread.sleep(2000);
        t.interrupt();
    }
}
```
程序运行结果如图1 - 53所示。

![image](https://github.com/user-attachments/assets/335fc806-dbde-499f-b054-7872da8bab41)


图1 - 53 线程成功停止

相比“抛异常”法，虽然使用“return;”在代码结构上可以更加方便地停止线程，不过还是建议使用“抛异常”法，因为该方法可以在catch块中对异常的信息进行统一处理。下面用具体示例来说明。使用“return;”来设计代码：
```java
public class MyThread extends Thread {
    @Override
    public void run() {
        //insert操作
        if (this.interrupted()) {
            System.out.println("写入log info");
            return;
        }
        //update操作
        if (this.interrupted()) {
            System.out.println("写入log info");
            return;
        }
        //delete操作
        if (this.interrupted()) {
            System.out.println("写入log info");
            return;
        }
        //select操作
        if (this.interrupted()) {
            System.out.println("写入log info");
            return;
        }
        System.out.println("for for for for for");
    }
}
```
在每个“return;”代码前都要搭配一个写入日志的代码，这样会使代码出现冗余，并没有集中处理日志，不利于代码的阅读与扩展，这时可以使用“抛异常”法来简化这段代码：
```java
public class MyThread2 extends Thread {
    @Override
    public void run() {
        try {
            //insert操作
            if (this.interrupted()) {
                throw new InterruptedException();
            }
            //update操作
            if (this.interrupted()) {
                throw new InterruptedException();
            }
            //delete操作
            if (this.interrupted()) {
                throw new InterruptedException();
            }
            //select操作
            if (this.interrupted()) {
                throw new InterruptedException();
            }
            System.out.println("for for for for for");
        } catch (InterruptedException e) {
            System.out.println("写入log info");
            e.printStackTrace();
        }
    }
}
```
写入日志的功能在catch块被集中统一处理了，代码风格更加规范。

### 1.12 暂停线程

暂停线程意味着此线程还可以恢复运行，在Java多线程中可以使用suspend()方法暂停 



